# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    max-connections: 2000
  #    connection-timeout: 1000
  port: 80
  servlet:
    context-path:
    session:
      cookie:
        http-only: true

spring:
  datasource:
    druid:
      #MySQL
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@10.144.15.222:1521:wsdb
      username: dky
      password: Naridky_123$
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      #Oracle需要打开注释
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #login-username: admin
        #login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: false
        wall:
          config:
            multi-statement-allow: true
  messages:
    encoding: UTF-8
    basename: i18n/messages
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    database: 0
    host: 192.168.10.10
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  activiti:
    check-process-definitions: false

fdfs:
  so-timeout: 600000
  connect-timeout: 6000
  tracker-list:            #TrackerList参数,支持多个
    - 192.168.10.10:22122

# 是否开启redis缓存  true开启   false关闭
link.redis.open: false

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: io.link.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: ID_WORKER
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
package:
  style: @project.packaging@
minio:
  db_host: rm-8vbykx31601qryjj33o.mysql.zhangbei.rds.aliyuncs.com
  db_port: 3306
  db_name: studio
  db_user: hrtuoyu
  db_password: B&^fnt!o^5CDH5V*
  db_timeout: 100
  # address: http://47.92.203.176
  address: http://192.168.2.181
  port: 9000
  ak: minioadmin
  sk: minioadmin
  bucket: eml-studio
  # <!--gateway配置-->
  gateway:
    host: 127.0.0.1
    port: 5000
    # <!--HDFS目录配置-->
hdfs:
  app_workspace: /EML/oozie
  draft_path: /EML/draft
  dataset_path: /EML/Data
  module_path: /EML/Modules
